### ISSUE TITLE
Internationaal?

### ISSUE THREAD

**Issue by Clinque** [dbeerpedia/general#14]
De intentie was om internationaal te gaan, beginnende bij de Nederlandse craft brouwerijen, maar alles wat ik nu zie, is in het Nederlands. 

We moeten even bepalen wat we wanneer in het Engels doen of wellicht al in een vroeg stadium overgaan op 'English-only'.  Dan kunnen we ook andere (niet nederlandstalige) bier en linked data experts aanhaken als we de eerste basis hebben uitgewerkt.

**Comment by dvh** [comment]
Eens! Maar tot die tijd lijkt het me goed om zo min mogelijk drempels te hebben totdat we echt lekker bezig zijn. Op het moment dat we switchen naar Engels krijgen we waarschijnlijk vanzelf meer contributors, en hoewel dat een goed ding is moeten we wel een beginnetje hebben om goed mee voor de dag te komen.

**Comment by Clinque** [comment]
Helemaal prima.
