### ISSUE TITLE
Communicatie via Slack of Gitter

### ISSUE THREAD

**Issue by pmaria** [dbeerpedia/general#15]
Is het een idee om een Slack of Gitter kanaal op te tuigen om de interactie te bevorderen?

**Comment by erwinfolmer** [comment]
lijkt mij een goeie!

**Comment by dvh** [comment]
Zoals besproken in Haarlem is er een Slack kanaal opgetuigd: https://dbeerpedia.slack.com. Helaas ondersteunt de gratis variant van Slack alleen nog maar toegang op uitnodiging... Via https://join.slack.com/dbeerpedia/signup kan momenteel iedereen met een e-mailadres van een van onderstaande domeinen inloggen:

- kadaster.nl
- freshheads.com
- apiwise.nl
- semaku.com
- taxonic.com
- geonovum.nl
- corralict.nl
- ordina.nl
- bdvc.nl
- ecp.nl
